### PR TITLE
My finished subuission 

### PR DESCRIPTION
**Pull request by Ousman37**
Please review My social media app for developer site.

### CODE REVIEW

**Comment by Ousman37** [comment]
I’m satisfied with  submission!

**Review by Ousman37 — COMMENTED** [review]
Please review my social media  app developer site.

**Comment by Ousman37** [comment]
Test

**Review by Ousman37 — COMMENTED** [review]
please review my work

**Comment by Ousman37** [comment]
I am trying to upload the site  to netlify but  something went wrong here.

**Comment by Fermain** [comment]
Hey, I don't see any of your work here?

**Comment by Fermain** [comment]
Bootstrap is not in use at all in this project. At present it cannot pass as many requirements are missing. Review them here: https://noroff-content.gitlab.io/feu/css-frameworks/marking-criteria.html

You must import, customise and use bootstrap to pass this assessment.

**Comment by Ousman37** [comment]
Hello!  
Please, can you review my  project I have implement  bootstrap now.

**Comment by Fermain** [comment]
Hey Didi, the reason I don't see your changes is because they have already been merged into `main`.

This is not a big problem, but in future assignments, you will need to get this right. Abi posted a video about how to resolve this, I am trying to find it now.

**Review by Fermain — CHANGES_REQUESTED** [review]
This is a good looking layout and there is a lot of work that has gone into it, but I think you have misunderstood the brief. Part of the marking criteria requires **Bootstrap Customisation** - you are not using Bootstrap at all in this submission.

Considering the effort you've put in and the quality of the product, I don't want to tell you to do this from scratch. Having said that, adapting the project to Bootstrap might be quite difficult. I will think of a compromise and we can chat about it offline.

**Pull request merged**
